[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/update"
  to = "/.netlify/functions/update"
  status = 200

[[redirects]]
  from = "/getall"
  to = "/.netlify/functions/get/getall"
  status = 200

[[redirects]]
  from = "/get/*"
  to = "/.netlify/functions/get/:splat"
  status = 200
